### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by snvoid** [AronAman/skillshare-dl#1]
Getting the following

Traceback (most recent call last):
  File "skillshare-dl.py", line 10, in <module>
    dl.download_course_by_url(url, True, True)
  File "/content/skillshare-downloader/code/skillshare-dl/skillshare.py", line 36, in download_course_by_url
    self.download_course_by_class_id(class_id, boolSubtitle, boolResources)
  File "/content/skillshare-downloader/code/skillshare-dl/skillshare.py", line 104, in download_course_by_class_id
    assert video_id, 'Failed to read video ID from data'
AssertionError: Failed to read video ID from data

**Comment by ogeeDeveloper** [comment]
I am getting the same error too, it seems like the cookie doesn't regenerate
